export const categories = [
    { id: 9, name: "General Knowledge", quote: "Expand your horizons." },
    { id: 10, name: "Books", quote: "Dive into literary worlds." },
    { id: 11, name: "Film", quote: "Experience cinematic magic." },
    { id: 12, name: "Music", quote: "Feel the rhythm of the world." },
    { id: 13, name: "Musicals & Theatres", quote: "Enjoy the spectacle." },
    { id: 14, name: "Television", quote: "Tune into your favorite shows." },
    { id: 15, name: "Video Games", quote: "Play your heart out." },
    { id: 16, name: "Board Games", quote: "Have fun with friends and family." },
    { id: 17, name: "Nature", quote: "The mysteries of the universe." },
    { id: 18, name: "Computers", quote: "Explore the digital frontier." },
    { id: 19, name: "Mathematics", quote: "Solve the puzzle of numbers." },
    { id: 20, name: "Mythology", quote: "Discover ancient legends." },
    { id: 21, name: "Sports", quote: "Feel the thrill of the game." },
    { id: 22, name: "Geography", quote: "Travel the world from home." },
    { id: 23, name: "History", quote: "Learn from the past." },
    { id: 24, name: "Politics", quote: "Understand the forces that shape our world." },
    { id: 25, name: "Art", quote: "Experience the beauty of creativity." },
    { id: 26, name: "Celebrities", quote: "Get the latest on your favorite stars." },
    { id: 27, name: "Animals", quote: "Explore the wild side of life." },
    { id: 28, name: "Vehicles", quote: "Discover the world of machines." },
    { id: 29, name: "Comics", quote: "Colorful stories and characters." },
    { id: 30, name: "Gadgets", quote: "Stay updated with the latest tech." },
    { id: 31, name: "Anime & Manga", quote: "Dive into Japanese pop culture." },
    { id: 32, name: "Cartoon", quote: "Relive childhood favorites." },
];
